### ISSUE TITLE
Copy travis + mergify + SBT setup

### ISSUE THREAD

**Issue by DanielaSfregola** [DanielaSfregola/zucchini#2]
Copy them from an existing project, a good candidate could be https://github.com/DanielaSfregola/random-data-generator-magnolia

**Comment by DanielaSfregola** [comment]
Not closing this one yet, as we need to update the version of zucchini to 0.1-SNAPSHOT and remove some not needed dependencies - @KXA194 let me know if you can do that in a future PR. If not, I'll have a look.

Cheers,
Daniela

**Comment by KXA194** [comment]
Not sure what is not needed from the build.sbt. @DanielaSfregola can you please help on this?

**Comment by DanielaSfregola** [comment]
Resolved by #5: closing ticket.
